### ISSUE TITLE
HW: Proof of concept 08/06

### ISSUE THREAD

**Issue by kbrimm** [Plantalytics/plantalytics-hardware#13]
- [ ] Collects sensor data
  - [ ] Temperature
  - [ ] Humidity
  - [ ] Leaf wetness
- [ ] Transmits data via LoraWAN
- [ ] Goes to sleep for 5 minutes
